title = "Digital Student Assistant gitleaks config"

[extend]
# Use Gitleaks default built-in rules.

[allowlist]
description = "ignore non-sensitive patterns"
paths = [
  "EVIDENCE/",
]
commits = []
regexes = [
  '''SECRET_DO_NOT_USE''',
]
