services:
  postgres_master:
    container_name: web_data
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
    profiles: ["dev"]
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_name"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped


  # vector_db:
  #   image:
  #   ports:
  #     - "5434:5432"
  #   environment:
  #     - name=value
  #   profiles:
  #     - ["dev"]
  #   volumes:
  #     - volumeName:containerPath:ro
  #   healthcheck:
  #     test: ["executable", "arg"]
  #     interval: 20s
  #     timeout: 10s
  #     retries: 5
  #     start_period: unless-stopped

  web:
    container_name: web_service
    build:
      context: ../services/web
    depends_on:
      postgres_master:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - ../services/web/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=config.settings.dev
      - DATABASE_URL=${DEV_DATABASE_URL:-postgresql+psycopg2://db_user:db_pass@postgres_master:5432/db_name}
    profiles: ["dev"]
    # volumes:
    #   - volumes volumes
    # tmpfs:
    #   - some
    read_only: true
    security_opt:
      - no-new-privileges:true
      - seccomp=../security/seccomp/default.json
    cap_drop:
      - ALL
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys,urllib.request as u; u.urlopen('http://127.0.0.1:8000/health').read(); sys.exit(0)"]
      interval: 30s
      timeout: 3s
      retries: 3
    user: "1000:1000"


  ml:
    container_name: ml_service
    build:
      context: ../services/ml
    # depends_on:
    #   vector_db:
    #     condition: service_healthy
    ports:
      - "8001:8000"
    env_file:
      - ../services/ml/.env
    environment:
      - PYTHONUNBUFFERED=1
    profiles: ["dev"]
    volumes:
      - app-data:/app/data
    tmpfs:
      - /tmp:rw,size=64m
    read_only: true
    security_opt:
      - no-new-privileges:true
      - seccomp=../security/seccomp/default.json
    cap_drop:
      - ALL
    pids_limit: 120
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys,urllib.request as u; u.urlopen('http://127.0.0.1:8000/health').read(); sys.exit(0)"]
      interval: 30s
      timeout: 3s
      retries: 3
    user: "1000:1000"

volumes:
  app-data:
    driver: local
  pg-data:
    driver: local
